apiVersion: v1
kind: Service
metadata:
  name: motorola-api-service
spec:
  type: NodePort
  selector:
    app: motorola-api
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080
